### ISSUE TITLE
Migration is "hard-labeled" with 7.0

### ISSUE THREAD

**Issue by gbudiman** [basecamp/console1984#18]
Is there a specific reason why it's locked to 7.0? Or just an oversight? :)

https://github.com/basecamp/console1984/blob/74e8258d843ca4cb2d59bcfefa91f83de1aee331/db/migrate/20210517203931_create_console1984_tables.rb#L1

**Comment by jorgemanrubia** [comment]
Hey @gbudiman thanks for the feedback. Versioning migrations lets Rails know which defaults it should apply, in case they change in future versions. `console1984` requires Active Record Encryption, which is a Rails 7 feature, so this should be good. Are you on Rails 6 trying to use the gem?

**Comment by edariedl** [comment]
Hey @jorgemanrubia, I tried the  exactly same thing to run it with Rails 6. Is there a way how to get around it or the only way is to run on Rails `main` branch?

**Comment by jorgemanrubia** [comment]
I am afraid that's correct @edariedl , sorry about the confusion here. I will add a note in the readme to make that clear since it's certainly not obvious at all.

**Comment by edariedl** [comment]
That's totally fine, looking forward to Rails 7 then :). Thanks for the amazing work on AR encryption as well as other things 🥇.
