### ISSUE TITLE
Bypass audit table protections by opening a direct connection with the database

### ISSUE THREAD

**Issue by gregmolnar** [basecamp/console1984#22]
I need to admit that https://github.com/basecamp/console1984/pull/20 made this a lot more robust, but it can still be bypassed by using a low level database connection. A Postgresql example:

```
# if you need to get the database connection config: ActiveRecord::Base.send(:resolve_config_for_connection, :development)
conn = PG::Connection.open(:dbname => 'rails_edge_development')
conn.exec "delete from console1984_sessions"
```

**Comment by jorgemanrubia** [comment]
An update: working on another batch of protections and improvements to prevent this and others. 

Thanks for these reports @gregmolnar.

**Comment by jorgemanrubia** [comment]
Fixed in #26.

I still have a pending patch to prevent using dynamic code evaluation to circumvent static controls (e.g: `eval` or `instance_eval`). Will work on that on a separated PR.

**Comment by gregmolnar** [comment]
@jorgemanrubia ping me when that pending patch is done and I will have another stab at bypassing it.

**Comment by jorgemanrubia** [comment]
Thanks @gregmolnar. I merged those changes in https://github.com/basecamp/console1984/pull/27 and released 0.1.8. I appreciate the help looking for vulns🙏.

**Comment by jorgemanrubia** [comment]
@gregmolnar I am preparing yet another round of protection improvements :). I'll let you know here when they're ready.

**Comment by jorgemanrubia** [comment]
There it goes @gregmolnar https://github.com/basecamp/console1984/pull/28. Version 0.1.9 released with that one.
