### ISSUE TITLE
Question? Running in API only mode

### ISSUE THREAD

**Issue by superscott** [basecamp/console1984#25]
Hi! 
So was looking forward to trying this out, but I get the following error when running with a Rails app that is in `api_only` mode and this happens when trying to install the migration. 

`rails console1984:install:migrations`

```
        16: from app/config/environment.rb:5:in `<main>'
	15: from /.rvm/gems/ruby-2.7.2/gems/railties-6.1.3.2/lib/rails/application.rb:384:in `initialize!'
	14: from /.rvm/gems/ruby-2.7.2/gems/railties-6.1.3.2/lib/rails/initializable.rb:60:in `run_initializers'
	13: from /.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	12: from /.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	11: from /.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	10: from /.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
	 9: from /.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
	 8: from /.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 7: from /.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 6: from /.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 5: from /.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	 4: from /.rvm/gems/ruby-2.7.2/gems/railties-6.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	 3: from /.rvm/gems/ruby-2.7.2/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `run'
	 2: from /.rvm/gems/ruby-2.7.2/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
	 1: from /.rvm/gems/ruby-2.7.2/gems/audits1984-0.1.1/lib/audits1984/engine.rb:22:in `block in <class:Engine>'
/.rvm/gems/ruby-2.7.2/gems/railties-6.1.3.2/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x00007fec796d75a0> (NoMethodError)
```

Obviously I'm still running Rails6 - but I am pretty sure this error is unrelated to that and this is specific to being run on an api only application. I'm kinda missing where exactly the assets are being looked up from, but searching the repo [I find this in the tests files](https://github.com/basecamp/console1984/blob/74e8258d843ca4cb2d59bcfefa91f83de1aee331/test/dummy/config/initializers/assets.rb#L4) which that line throws the same error if I just type into `rails console`.

I know this might not be a priority to fix (or even on the roadmap) but hopefully there might be a tweak we can make to ignore anything to do with assets (and leave the assets to audits1984?).
Either way - thanks for this and looking forward to a response! 

Thanks!
-scott

**Comment by jorgemanrubia** [comment]
Hey @superscott, is it possible that you have added `audits1984` to your `Gemfile`? `console1984` doesn't reference `audits1984` (the dependency is in the other direction: `audits1984` -> `console1984`). Your app seems to be trying to initialize `audits1984` so my guess is that you are including it in your `Gemfile`. Try removing it from the `Gemfile`.

Another problem I am afraid you'll find is that `console1984` requires Active Record Encryption, which is an upcoming Rails 7 feature, no available in Rails 6.

**Comment by superscott** [comment]
hi @jorgemanrubia you're right - it was audits1984 and removing it gave me the `undefined method 'encrypts'` error. 
sorry about that! thanks!
