### ISSUE TITLE
NoMethodError: undefined method `thread_mattr_accessor' when generating migrations

### ISSUE THREAD

**Issue by lunaisnotaboy** [basecamp/console1984#40]
Whenever you run `rails console1984:install:migrations`, you receive a NoMethodError.

Output of the command:

```
rails aborted!
NoMethodError: undefined method `thread_mattr_accessor' for Console1984:Module
/home/robert/critter/config/application.rb:18:in `<main>'
/home/robert/critter/Rakefile:6:in `<main>'
bin/rails:6:in `<main>'
(See full trace by running task with --trace)
```

**Comment by jorgemanrubia** [comment]
@lunaisnotaboy [v0.1.20](https://github.com/basecamp/console1984/releases/tag/v0.1.20) should fix this problem. We hit it ourselves after updating to official Rails 7.0 😅. I gave it a try and it worked for me but please let me know if it's still failing for you.

**Comment by lunaisnotaboy** [comment]
@jorgemanrubia The problem occured on v0.1.20. Apologies for not saying so in the beginning.

**Comment by jorgemanrubia** [comment]
On a fresh Rails app it worked for me with 0.1.20. Are you certain you are on that version (you can check `Gemfile.lock` and, also, make sure you stop spring `spring stop` if you are using it):

```
[main][~/Projects/test_console]$ bin/rails console1984:install:migrations
Copied migration 20211222144357_create_console1984_tables.console1984.rb from console1984
[main][~/Projects/test_console]$ cat Gemfile.lock | grep console1984
    console1984 (0.1.20)
  console1984
[main][~/Projects/test_console]$ bin/rails --version
Rails 7.0.0
```

**Comment by lunaisnotaboy** [comment]
Still no. I reinstalled everything, and made sure that it wasn't just the project.

The following link contains my `Gemfile` and `Gemfile.lock` files: https://gist.github.com/lunaisnotaboy/7dd1097eed415fa43816fa02fed63070

I am running everything with the latest versions, and Spring was not running.

**Comment by jorgemanrubia** [comment]
Hey Luna I can reproduce with that `Gemfile`, thanks! Taking a look.

**Comment by lunaisnotaboy** [comment]
Would the project help? Nothing else is in there, as it's a project that was recently generated.

**Comment by jorgemanrubia** [comment]
No it's ok, I can work with this, thanks!

**Comment by jorgemanrubia** [comment]
Released version 0.1.22 addressing this problem. I'll update audits1984 next (there is another error with the upgrade).

**Comment by jorgemanrubia** [comment]
Oh no sorry, it was a problem with my test project and web packer. I think it all should be good if you fetch the latest console1984 @lunaisnotaboy

**Comment by lunaisnotaboy** [comment]
Thanks!
