### ISSUE TITLE
Why set username ?

### ISSUE THREAD

**Issue by lazaronixon** [basecamp/console1984#71]
What is the objective of the`CONSOLE_USER` or the `ask_for_username_if_empty` if i can inform any name here, how do you use it in 37signal?

**Comment by jorgemanrubia** [comment]
@lazaronixon sorry for the delay here. That option is meant for scenarios where it's not possible to provide the acting user. For example, imagine someone SSH into a box with a generic user and starts a console. The best scenario is not allowing this, but in such situation the option is handy, knowing that it won't really prevent against malicious actors, as @stevenhan2 points out.

In 37signals we rely on `CONSOLE_USER` being set by the tooling we use to start rails consoles (we use two different in-house tools depending on whether the target app is on-prem or in the cloud).
