### ISSUE TITLE
Receiving notifications for specific commands

### ISSUE THREAD

**Issue by lfv89** [basecamp/console1984#92]
Hello @jorgemanrubia. I'd like to receive a notification every time a specific command is executed (for instance, every time a `decrypt!` is invoked). 

Is that something you'd consider adding? I'd be glad to jump on it myself, so If you have any suggestions on such implementation I'd love to hear it.

**Comment by jorgemanrubia** [comment]
You could configure a custom `session_logger` that logged commands however you wanted. I think that would be the right way to add what you want. Would that work for your use case? I don't see such logger as general-purpose enough to include in this gem though.
