### ISSUE TITLE
Protecting ENV 

### ISSUE THREAD

**Issue by lfv89** [basecamp/console1984#93]
Hey @jorgemanrubia,

I've been trying out a way to prevent direct access to certain `ENV` values in the console. The gem already takes care of Rails Credentials, so I thought it'd be a nice addition to the gem doing something similar for `ENV`. If you're up for it, I'd be happy to open a PR so we could work together on this feature.

**Comment by jorgemanrubia** [comment]
That's a great idea. Please go for it 🙏
