### ISSUE TITLE
Encrypted attributes printed in cleartext in error message

### ISSUE THREAD

**Issue by magnusvk** [basecamp/console1984#98]
We've recently started using console1984. Thanks for the fantastic gem! We just noticed an issue where it leaks encrypted data, however, even without using `decrypt`. Simply take any model with encrypted attributes and attempt to call a method on it that doesn't exist. `model.foobar` => `'method_missing': undefined method 'last4' for #<inspect output with decrypted values>`

I was curious if this is a known issue? Is this caused by a combination with another gem on our end? Where would we start to try and fix this?

**Comment by jorgemanrubia** [comment]
Thanks a lot for the report @magnusvk. This was a serious one! I'm surprised we didn't find it until now.

https://github.com/basecamp/console1984/pull/99 will fix this.

**Comment by jorgemanrubia** [comment]
Released 0.1.30 with the patch.

**Comment by magnusvk** [comment]
Wonderful, thank you!
